package com.meed223.rms_editor.elements;



import java.util.ArrayList;

public class RMS {
    /* Object Info */
    public String mapName;

    /* RMS Map Constants */
    //public ArrayList<mapDefinition> mapDefs;      // For random at start of maps, for deciding if snowy, etc.
    public ArrayList<MapConst> mapConsts;
    private String baseTerrain;

    /* RMS Generation Objects */
    private Player player;
    private ArrayList<Land> landGeneration;
    private ArrayList<Terrain> terrainGeneration;
    private ArrayList<Object> objectGeneration;
    private ArrayList<Elevation> elevationGeneration;
    private ArrayList<Connection> teamConnectionGeneration;
    private ArrayList<Connection> playerConnectionGeneration;
    private ArrayList<Connection> allLandConnectionGeneration;
    private Cliff cliffGeneration;

    /* Constructor(s) */
    public RMS() {
        // Object info
        mapName = null;

        // Map constants
        mapConsts = new ArrayList<>();
        baseTerrain = null;

        // Generation objects
        player = new Player();
        landGeneration = new ArrayList<>();
        terrainGeneration = new ArrayList<>();
        objectGeneration = new ArrayList<>();
        elevationGeneration = new ArrayList<>();
        teamConnectionGeneration = new ArrayList<>();
        playerConnectionGeneration = new ArrayList<>();
        allLandConnectionGeneration = new ArrayList<>();
        cliffGeneration = new Cliff();
    }

    /* Hash Code */
    @Override
    public int hashCode() {
        int hash = 7;
        hash = 5 * hash + mapName.hashCode();
        hash = 7 * hash + mapConsts.hashCode();
        hash = 5 * hash + baseTerrain.hashCode();
        hash = 7 * hash + player.hashCode();
        hash = 5 * hash + landGeneration.hashCode();
        hash = 7 * hash + terrainGeneration.hashCode();
        hash = 5 * hash + objectGeneration.hashCode();
        hash = 7 * hash + elevationGeneration.hashCode();
        hash = 5 * hash + teamConnectionGeneration.hashCode();
        hash = 7 * hash + playerConnectionGeneration.hashCode();
        hash = 5 * hash + allLandConnectionGeneration.hashCode();
        hash = 7 * hash + cliffGeneration.hashCode();
        return hash;
    }

    /* Generate RMS */
    @Override
    public String toString() {
        StringBuilder rms = new StringBuilder();

        /* Map information */
        rms.append("/* ===[ ");
        rms.append(mapName);
        rms.append(" ]=== */\n");
        rms.append("/* Generated by Meed223's RMS Editor */\n\n");

        /* Map Constants */
        rms.append("/* ---[ Map Constants ]--- */\n");
        for (MapConst mapConst : mapConsts) {
            rms.append(mapConst.toString());
        }


        /* <PLAYER_SETUP> */
        rms.append(player.toString());

        /* <LAND_GENERATION> */
        rms.append("\n<LAND_GENERATION>\n");
        rms.append("\nbase_terrain ");
        rms.append(baseTerrain);
        rms.append("\n");
        for (Land land : landGeneration) {
            rms.append(land.toString());
        }

        /* <ELEVATION_GENERATION> */
        rms.append("\n<ELEVATION_GENERATION>\n");
        for (Elevation elevation : elevationGeneration) {
            rms.append(elevation.toString());
        }

        /* <CLIFF_GENERATION> */
        rms.append(cliffGeneration.toString());

        /* <TERRAIN_GENERATION> */
        rms.append("\n<TERRAIN_GENERATION>\n");
        for (Terrain terrain : terrainGeneration) {
            rms.append(terrain.toString());
        }

        /* <CONNECTION_GENERATION> */
        rms.append("\n<CONNECTION_GENERATION>\n");
        rms.append("\ncreate_connect_teams_lands {");
        for (Connection connection : teamConnectionGeneration) {
            rms.append(connection.toString());
        }
        rms.append("\n}");
        rms.append("\ncreate_connect_all_players_lands {");
        for (Connection connection : playerConnectionGeneration) {
            rms.append(connection.toString());
        }
        rms.append("\n}");
        rms.append("\ncreate_connect_all_lands {");
        for (Connection connection : allLandConnectionGeneration) {
            rms.append(connection.toString());
        }
        rms.append("\n}\n");

        /* <OBJECTS_GENERATION> */
        rms.append("\n<OBJECT_GENERATION>\n");
        for (Object object : objectGeneration) {
            rms.append(object.toString());
        }

        return rms.toString();
    }

    /* Getters & Setters */

    public String getMapName() {
        return mapName;
    }

    public void setMapName(String mapName) {
        this.mapName = mapName;
    }

    public ArrayList<MapConst> getMapConsts() {
        return mapConsts;
    }

    public void setMapConsts(ArrayList<MapConst> MapConsts) {
        this.mapConsts = MapConsts;
    }

    public String getBaseTerrain() {
        return baseTerrain;
    }

    public void setBaseTerrain(String baseTerrain) {
        this.baseTerrain = baseTerrain;
    }

    public Player getPlayer() {
        return player;
    }

    public void setPlayer(Player player) {
        this.player = player;
    }

    public ArrayList<Land> getLandGeneration() {
        return landGeneration;
    }

    public void setLandGeneration(ArrayList<Land> landGeneration) {
        this.landGeneration = landGeneration;
    }

    public ArrayList<Terrain> getTerrainGeneration() {
        return terrainGeneration;
    }

    public void setTerrainGeneration(ArrayList<Terrain> terrainGeneration) {
        this.terrainGeneration = terrainGeneration;
    }

    public ArrayList<Object> getObjectGeneration() {
        return objectGeneration;
    }

    public void setObjectGeneration(ArrayList<Object> objectGeneration) {
        this.objectGeneration = objectGeneration;
    }

    public ArrayList<Elevation> getElevationGeneration() {
        return elevationGeneration;
    }

    public void setElevationGeneration(ArrayList<Elevation> elevationGeneration) {
        this.elevationGeneration = elevationGeneration;
    }

    public ArrayList<Connection> getTeamConnectionGeneration() {
        return teamConnectionGeneration;
    }

    public void setTeamConnectionGeneration(ArrayList<Connection> teamConnectionGeneration) {
        this.teamConnectionGeneration = teamConnectionGeneration;
    }

    public ArrayList<Connection> getPlayerConnectionGeneration() {
        return playerConnectionGeneration;
    }

    public void setPlayerConnectionGeneration(ArrayList<Connection> playerConnectionGeneration) {
        this.playerConnectionGeneration = playerConnectionGeneration;
    }

    public ArrayList<Connection> getAllLandConnectionGeneration() {
        return allLandConnectionGeneration;
    }

    public void setAllLandConnectionGeneration(ArrayList<Connection> allLandConnectionGeneration) {
        this.allLandConnectionGeneration = allLandConnectionGeneration;
    }

    public Cliff getCliffGeneration() {
        return cliffGeneration;
    }

    public void setCliffGeneration(Cliff cliffGeneration) {
        this.cliffGeneration = cliffGeneration;
    }
}
